services:
  - type: web
    name: insta-parser-bot
    env: python
    plan: free
    pythonVersion: 3.11
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: python bot.py
